apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    deleteLabel: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        deleteLabel: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.service.image }}
          imagePullPolicy: Always
          ports:
            - name: "{{ .Chart.Name }}-port"
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      restartPolicy: Always