name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Write out the kubeconfig info
        env:
          MY_SECRET: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$MY_SECRET" | base64 -d >> /tmp/config
          chmod 0600 /tmp/config

      - name: Instal deps
        run: curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash

      - name: Deploy DB
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          helm upgrade --install postgres ./kubernetes/postgres
      
      - name: Deploy API
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          kubectl config view
          helm upgrade --install cars ./kubernetes/cars
          kubectl apply -f ./kubernetes/ingress.yaml


      - name: Update /etc/hosts
        run: sudo echo "${{ secrets.KUBE_IP }} maxermu.disp.com" | sudo tee -a /etc/hosts

      - name: Wait 120s
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"